### ISSUE TITLE
correcciones

### ISSUE THREAD

**Issue by lspigariol** [pdep-utn-frd/2019-tpwgame-r#1]
me gusta la idea, 
@rodrigodavilalg @ValentinMorali @davidmarco12 

lo primero a remarcar es en relacion a su comenterio:
* El codigo no esta prolijo ya que lo que importaba era aprender y probar la libreria de wollokGame
 
el objetivo no era aprender la libreria game, sino usándola aprender a modelar en objetos.
no se si llamarle desprolijidad, pero hay mucho codigo repetitivo, por ejemplo todo el manejo de vida, lleno de ifs y valores arbitrarios. Se puede mejorar mucho, pasando por parametro los valores. Tengan en cuenta que los nombres de las imagenes son strings y se pueden concatenar haciendo algo asi como `"talcosa" + nro.toString() + ".png"`

una forma mas propia del paradigma de modelar los ataques es con objetos cura magia, etc, que cada uno tenga métodos polimórficos para alterar la vida, etc . de hecho hay un objeto ataqueheroe que esta por ahi sin mucho comportamiento.

desde la usabilidad, la muerte se podria manejar diferente, que se valide la vida. no entendi la logica de la tecla k. Algo util y no muy complicado es tener un reiniciar.

**Comment by lspigariol** [comment]
El otro dia estuvimos hablando, 
les hice un commit con avances
quedamos en que terminaban de hacer algunos ajustes en el juego.

@rodrigodavilalg @ValentinMorali @davidmarco12

**Comment by ValentinMorali** [comment]
Hola Lucas, quería ver si podrías volver a ver el juego, más que nada Personajes.wlk que es donde hubo modificaciones. Gracias

**Comment by lspigariol** [comment]
lo estaba viendo, vi que lo estan modificando en la direccion correcta, falta terminar de articularlo con lo anterior

por ejemplo: 
la logica de curar deberia pasar al nuevo objeto cura
algo similar con magia y los ataques especiales. pueden ser todos polimorficos, cada uno causa un efecto diferente en el heroe (que ahora hay uno, pero con muy poco esfuerzo -definir una clase en vez de un objeto suelto- podría haber mas)

bien lo de la imagen concatenando. si lo hicieran en el metodo image() se ahorraria de pedir que se actualice la imagen cada vez que hay un cambio.

**Comment by ValentinMorali** [comment]
Hola. Modelé los objetos Cura, Magia, Ataque Especial, e hice que tanto heroe como enemigo puedan utilizarlo y recibir los efectos.
No comprendí esta parte: "bien lo de la imagen concatenando. si lo hicieran en el metodo image() se ahorraria de pedir que se actualice la imagen cada vez que hay un cambio."

**Comment by lspigariol** [comment]
bien, lo veo mejor, se podria seguir puliendo, pero creo que ya se entiende para donde apunta el paradigma.
lo de las imagenes es para reforzar la idea de metodo/mensaje por sobre atributo/variable
Lo que la biblioteca WGAme requiere es poder enviarle un mensaje image() al objeto y así obtener el archivo a mostrar. No le importan/no ve los atributos. Entonces, se puede hacer

method image() {
// aca toda la logica de como obtener la imagen dependiendo de la vida, etc y  el return

El tp queda aprobado.
